FROM node:18
RUN apt-get update && apt-get install -y \
  libssl-dev \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY ./public ./public
COPY ./src ./src 
COPY ./index.html ./index.html
COPY ./package.json ./
COPY ./socket.js ./socket.js

RUN npm install
EXPOSE 3001
CMD ["npm","run","dev"]